'use-client';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import RecipeContextProvider from '@/app/components/recipe/recipeContext';
import RecipeStepsContextProvider from '@/app/components/recipesteps/recipeStepContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* ADD CONTEXT PROVIDERS FOR RECIPE STEPS AND RECIPES */}
        <RecipeContextProvider>
          <RecipeStepsContextProvider>{children}</RecipeStepsContextProvider>
        </RecipeContextProvider>
      </body>
    </html>
  );
}
